const translations = {
    en: {
        welcome: 'Welcome!',
        goodbye: 'Goodbye!',
        continue: 'Continue',
        enterTheCode: 'Enter the code',
        parents: 'Parents',
        chat: 'Chat',
        completedTasks: 'Completed tasks',
        getToKnowYourChild: 'Get to know your child',
        tenInsights: "10 insights from your child's activity in the last 7 days",
        changeEmail: 'Change email',
        changePassword: 'Change password',
        voiceInstructions: 'Voice instructions',
        textInstructions: 'Text instructions',
        support: 'Support',
        language: 'Language',
        logout: 'Logout',
        back: 'Back',
        settings: 'Settings',
        newPassword: 'New password',
        passwordMustContainAtLeast: 'Password must contain at least 1 uppercase letter',
        save: 'Save',
        age: 'Age',
        withMistakes: 'With mistakes',
        withoutMistakes: 'Without mistakes',
        totalTime: 'Total time',
        puzzlesSolved: 'Puzzles solved',
        overview: 'Overview',
        day: 'Day',
        week: 'Week',
        month: 'Month',
        cancel: 'Cancel',
        done: 'Done',
        openChat: 'Open chat',
        today: 'Today',
        login: 'Log in',
        signup: 'Sign up',
        hello: 'Hello',
        email: 'Email',
        password: 'Password',
        forgotPassword: 'Forgot password',
        continueWith: 'Continue with',
        iDontHaveAcc: 'I don’t have an account yet',
        iAlrHaveAcc: 'I already have an account',
        message: 'Message',
        selectLangToProceed: 'Select language to proceed',
        forgotUrPassword: 'Forgot your password',
        enterYourEmailAddressAnd: 'Enter your email address and we will send you instructions to reset your password',
        emailAddress: 'Email address',
        send: 'Send',
        backTo: 'Back to',
        letsPlay: "Let's play",
        mistakes: 'Mistakes',
        followInstructions: 'Follow instructions to proceed',
        thereIsALink: 'There’s a link sent to your email address. Please open it on this device.',
        openInbox: 'Open inbox',
        redendCode: 'Resend code',
        resendCodeIn: 'Resend code in',
        exit: 'Exit',
        backgroundMusic: 'Background music',
        childWithThisName: 'Child with this name already exists'
    },
    lv: {
        welcome: 'Laipni lūdzam!',
        goodbye: 'Uz redzēšanos!',
        continue: 'Turpināt',
        enterTheCode: 'Ievadiet kodu',
        parents: 'Vecāki',
        chat: 'Čats',
        completedTasks: 'Pabeigtie uzdevumi',
        getToKnowYourChild: 'Iepazīstiet savu bērnu',
        tenInsights: '10 atziņas no jūsu bērna aktivitātēm pēdējo 7 dienu laikā',
        changeEmail: 'Mainīt e-pastu',
        changePassword: 'Mainīt paroli',
        voiceInstructions: 'Balss norādījumi',
        textInstructions: 'Teksta norādījumi',
        support: 'Atbalsts',
        language: 'Valoda',
        logout: 'Izrakstīties',
        back: 'Atpakaļ',
        settings: 'Iestatījumi',
        newPassword: 'Jauna parole',
        passwordMustContainAtLeast: 'Parolei jābūt vismaz ar 1 lielo burtu',
        save: 'Saglabāt',
        age: 'Vecums',
        withMistakes: 'Ar kļūdām',
        withoutMistakes: 'Bez kļūdām',
        totalTime: 'Kopējais laiks',
        puzzlesSolved: 'Atrisinātie uzdevumi',
        overview: 'Pārskats',
        day: 'Diena',
        week: 'Nedēļa',
        month: 'Mēnesis',
        cancel: 'Atcelt',
        done: 'Izpildīts',
        openChat: 'Atvērt čatu',
        today: 'Šodien',
        login: 'Pieteikties',
        signup: 'Reģistrēties',
        hello: 'Sveiki',
        email: 'E-pasts',
        password: 'Parole',
        forgotPassword: 'Aizmirsi paroli?',
        continueWith: 'Turpināt ar',
        iDontHaveAcc: 'Man vēl nav konta',
        iAlrHaveAcc: 'Man jau ir konts',
        message: 'Ziņojums',
        selectLangToProceed: 'Izvēlieties valodu, lai turpinātu',
        forgotUrPassword: 'Aizmirsi savu paroli',
        enterYourEmailAddressAnd: 'Ievadiet savu e-pasta adresi, un mēs nosūtīsim norādījumus paroles atiestatīšanai',
        emailAddress: 'E-pasta adrese',
        send: 'Nosūtīt',
        backTo: 'Atpakaļ uz',
        letsPlay: 'Spēlēsim!',
        mistakes: 'Kļūdas',
        followInstructions: 'Izpildiet norādījumus, lai turpinātu',
        thereIsALink: 'Uz jūsu e-pasta adresi ir nosūtīta saite. Lūdzu, atveriet to šajā ierīcē.',
        openInbox: 'Atvērt pastkasti',
        resendCode: 'Atkārtoti nosūtīt kodu',
        resendCodeIn: 'Atkārtoti nosūtīt kodu pēc',
        exit: 'Iziet',
        backgroundMusic: 'Fona mūzika',
        childWithThisName: 'Bērns ar šādu vārdu jau eksistē'
    }
};

export default translations;


// ru: {
    //     welcome: 'Добро пожаловать!',
    //     goodbye: 'До свидания!',
    //     continue: 'Продолжить'
    // },
    // es: {
    //     welcome: '¡Bienvenido!',
    //     goodbye: '¡Adiós!',
    //     continue: 'Continuar'
    // },
    // fr: {
    //     welcome: 'Bienvenue!',
    //     goodbye: 'Au revoir!',
    //     continue: 'Continuer'
    // },
    // sv: {
    //     welcome: 'Välkommen!',
    //     goodbye: 'Adjö!',
    //     continue: 'Fortsätt'
    // },
    // da: {
    //     welcome: 'Velkommen!',
    //     goodbye: 'Farvel!',
    //     continue: 'Fortsæt'
    // }
